FROM python:3.10-slim

WORKDIR /app

# 系统依赖
RUN apt-get update && apt-get install -y \
    gcc \
    git \
    && rm -rf /var/lib/apt/lists/*

# 复制依赖
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# 只复制核心代码
COPY config /app/config
COPY crack /app/crack
COPY script /app/script

ENV PYTHONPATH=/app

CMD ["python","script/run.py"]